-- StructTech OS — reconciled file for ledger row 20260801175520
-- `organizations_add_supplier_tenant_type`, applied 2026-08-01 with no repo file.
--
-- OWNERSHIP: this migration is recorded against the Material Matrix series, but it
-- alters `public.organizations` — a StructTech OS table and the root of the tenancy
-- model (§4.5, D1) — and inserts a row into it. Ownership follows the table, not the
-- author, so the file is ours. Material Matrix reviews it before it lands, because it
-- creates their org row and they are authoritative about its contents.
--
-- PROVENANCE: the body below is the EXECUTED SQL, recovered verbatim from
-- `supabase_migrations.schema_migrations.statements` (313 bytes), per §7.1 Rule 1 —
-- a reconciled file records what RAN, not what the schema should say today.
--
-- THE DIVERGENCES FROM THE EXECUTED TEXT ARE FOUR, AND THEY ARE ENUMERATED IN FULL
-- (amended 2026-08-28. The 2026-08-27 header said "the two idempotency guards, and
-- nothing else is added" plus one removal — THREE. It under-counted by one, and the
-- item it missed is the most consequential change in the file. Material Matrix found
-- it by reading the file against the LEDGER rather than against this header.):
--   1. `if exists` ADDED to the constraint drop. The original was a bare DROP
--      CONSTRAINT and errored on statement one when replayed.
--   2. `where not exists` ADDED to the insert, which also changes the statement FORM
--      from `insert … values` to `insert … select … where not exists`. The original
--      INSERT was unguarded, so a replay created a SECOND 'Material Matrix' org with
--      a second id — which every org_id FK and `my_org_ids()` would then treat as a
--      distinct tenant. That is tenancy corruption, not a bookkeeping error.
--   3. **THE id IS SUPPLIED LITERALLY, AND THE ORIGINAL SUPPLIED NO id AT ALL.** The
--      executed statement was `INSERT INTO organizations (name, tenant_type) VALUES
--      ('Material Matrix', 'supplier')` — TWO columns. The id was GENERATED by the
--      column default. This file names a third column and writes
--      `1084baa8-0355-4298-9b98-b876a7581173` as a literal value.
--      **THIS IS THE LARGEST CHANGE IN THE FILE AND THE ENTIRE REASON ITEM 2 WORKS:**
--      a guard needs an IMMUTABLE identity to key on, and a generated id is not
--      something a file can key on, because the file never learns what was generated.
--      It is the difference between reproducing *a* row and reproducing *the* row.
--      Named third only because that is the order the statements read in; by weight
--      it is first.
--   4. The trailing `RETURNING id` is REMOVED — a consequence of the form change in
--      item 2. Nothing consumed that value (the ledger executed it as a bare
--      statement), so the removal is behaviourally inert, but it IS a divergence from
--      the executed text and is named rather than folded into "only the guards
--      changed."
--
-- THIS FILE IS A RECONSTRUCTION, NOT A TRANSCRIPTION, AND IT WILL FAIL THE
-- BYTE-IDENTITY TEST FOREVER — BY CONSTRUCTION, NOT BY DRIFT.
-- Reconciled files on this project are verified with
-- `md5(file) == md5(array_to_string(statements))`. **THIS ONE CANNOT PASS THAT CHECK
-- AND IS NOT EXPECTED TO.** The four divergences above are deliberate and two of them
-- — the literal id and the changed insert form — are load-bearing: removing either
-- one to win the hash would reintroduce the duplicate-org bug the file exists to
-- prevent. A future sweep across `_archive_pre_baseline/` will therefore return
-- exactly ONE failure, and it will be this file.
-- Recorded here so the reader neither burns a day diagnosing it nor — the worse
-- outcome — learns that md5 failures in this directory are normal. That second
-- outcome is the advisor problem (`CLAUDE.md` rule 9) wearing different clothes.
-- The executed text is preserved and addressable for anyone who wants to diff it:
-- `backups/a1_0_pre_baseline_20260823/ledger_statements/053__20260801175520__organizations_add_supplier_tenant_type.sql`
-- — 313 bytes, sha256_16 `1144d6e1ae9dbcf2`. Note also that the executed text is
-- UPPERCASE-keyword formatted where this file is lowercase, so the hashes would
-- differ even if the four semantic divergences did not exist.
--
-- STATEMENT ORDER IS LOAD-BEARING — DO NOT REORDER (verified by Material Matrix
-- 2026-08-28, on the live database, which is the half our clean restore could not
-- see). The CHECK constraint must be widened to admit `supplier` BEFORE the insert
-- runs; reversed, the insert fails the old constraint. MM also confirmed the LIVE
-- constraint matches this file's exactly, and that all three `tenant_type` values
-- (`internal`, `contractor`, `supplier`) are populated with one row each — so the
-- ADD CONSTRAINT validates cleanly on replay rather than aborting on an existing row.
-- **This file preserves that order because the EXECUTED TEXT had it, not because
-- anyone reasoned about it** — which is Rule 1 paying for itself, and is recorded
-- that way rather than claimed as foresight.
--
-- WHY THE GUARD KEYS ON THE id AND NOT ON name + tenant_type (amended 2026-08-27,
-- on Material Matrix's review of the 2026-08-23 version, which keyed on name):
-- `name` IS MUTABLE. Material Matrix bought a domain on 2026-08-27, so a rename is
-- live rather than hypothetical. After a rename, a name-keyed guard MATCHES NOTHING
-- and silently creates the exact duplicate the guard exists to prevent — at the one
-- moment nobody is watching for it, since a guarded file reads as safe.
-- THE GENERAL RULE, because it outlives this file: SPECIFYING THE id LITERALLY
-- REPRODUCES THE ROW THAT ACTUALLY RAN. That is §7.1 Rule 1 applied to a VALUE
-- rather than to a FILE. The name-keyed version reproduces *a* Material Matrix org;
-- this one reproduces *theirs*. Only one of those is a historical record.
--
-- `created_at` IS DELIBERATELY NOT PINNED, AND THIS IS THE BOUNDARY ON RULE 1:
-- RULE 1 REPRODUCES WHAT RAN; IT DOES NOT FABRICATE A HISTORY THE REPLAY DOES NOT
-- HAVE. `created_at` is an audit field nothing references, and forcing
-- 2026-08-01 17:55:20.888922+00 into a clean restore asserts a history that restore
-- does not have. Pin identity and payload; let time be time. **ON REPLAY, THIS ROW'S
-- `created_at` WILL DIFFER FROM PRODUCTION'S, AND THAT IS INTENDED** — recorded
-- because a DOCUMENTED divergence is a fact, while an UNDOCUMENTED one trains people
-- to ignore differences. (Material Matrix's reasoning, adopted 2026-08-27.)
--
-- DELIBERATELY NOT ADDED (controller decision 2026-08-23, re-affirmed 2026-08-27):
-- no unique index, no new column, no ON CONFLICT. A unique index on
-- organizations.name would decide, inside an idempotency fix, that two tenants may
-- never share a company name — a product question on a pooled multi-tenant OS, where
-- two "Smith Construction"s in different states is not far-fetched. That question is
-- logged in the backlog as org identity (name uniqueness vs a slug/external_key) and
-- gets its own task. Material Matrix reached the same conclusion independently, from
-- tenancy-root product concerns; the controller reached it from "this does not belong
-- inside an idempotency fix."
--
-- NOT APPLIED FROM THIS FILE. The change is already live in production; this file
-- exists so the ledger row becomes addressable. Verified idempotent by running it
-- TWICE against a clean restore on local PostgreSQL 17.11 — see §10, 2026-08-27.
-- The 2026-08-23 proof does NOT carry forward: it exercised a different guard.

alter table organizations
  drop constraint if exists organizations_tenant_type_check;

alter table organizations
  add constraint organizations_tenant_type_check
  check (tenant_type in ('internal', 'contractor', 'supplier'));

insert into organizations (id, name, tenant_type)
select '1084baa8-0355-4298-9b98-b876a7581173', 'Material Matrix', 'supplier'
where not exists (
  select 1 from organizations
  where id = '1084baa8-0355-4298-9b98-b876a7581173'
);
