alter table public.estimate_line_items
  add column scope_key text;

comment on column public.estimate_line_items.scope_key is
  'Tags a line item as generated by Guided mode from this site-visit-scope checklist key. Null for manual/free-typed lines. Never set by the UI directly — only upsert_estimate_scope_line_items() writes it.';

create unique index estimate_line_items_estimate_scope_key_uidx
  on public.estimate_line_items (estimate_id, scope_key)
  where scope_key is not null;

create or replace function public.upsert_estimate_scope_line_items(
  p_estimate_id uuid,
  p_items jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_status text;
  v_next_sort int;
  v_item jsonb;
begin
  select org_id, status into v_org_id, v_status
  from public.estimates where id = p_estimate_id;

  if v_org_id is null or v_org_id not in (select my_org_ids()) then
    raise exception 'estimate not found or not accessible: %', p_estimate_id;
  end if;

  if v_status in ('signed', 'void') then
    raise exception 'estimate % is locked (status: %) — line items can only change before signing', p_estimate_id, v_status;
  end if;

  select coalesce(max(sort_order) + 1, 0) into v_next_sort
  from public.estimate_line_items where estimate_id = p_estimate_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.estimate_line_items
      (org_id, estimate_id, scope_key, description, quantity, unit, unit_price, product_id, sort_order)
    values
      (v_org_id, p_estimate_id, v_item->>'scope_key', v_item->>'description',
       (v_item->>'quantity')::numeric, v_item->>'unit', 0, null, v_next_sort)
    on conflict (estimate_id, scope_key) where scope_key is not null
    do update set
      quantity = excluded.quantity,
      unit = excluded.unit,
      updated_at = now();

    v_next_sort := v_next_sort + 1;
  end loop;
end;
$$;

update public.tenant_modules
set config = config || jsonb_build_object(
  'scope_line_items', jsonb_build_object(
    'roof_area_sqft', jsonb_build_object('generates', true, 'description', 'Roof — tear off and replace', 'unit', 'sq', 'factor', 0.01),
    'gutters_lf', jsonb_build_object('generates', true, 'description', 'Gutters', 'unit', 'lf'),
    'fascia_lf', jsonb_build_object('generates', true, 'description', 'Fascia', 'unit', 'lf'),
    'soffit_lf', jsonb_build_object('generates', true, 'description', 'Soffit', 'unit', 'lf'),
    'pipe_boots', jsonb_build_object('generates', true, 'description', 'Pipe boots', 'unit', 'ea'),
    'roof_vents', jsonb_build_object('generates', true, 'description', 'Roof vents', 'unit', 'ea'),
    'osb_replacement_sheets', jsonb_build_object('generates', true, 'description', 'OSB replacement', 'unit', 'sheet'),
    'facets', jsonb_build_object('generates', false),
    'pitch_slope_notes', jsonb_build_object('generates', false),
    'roof_color', jsonb_build_object('generates', false),
    'roof_profile_style', jsonb_build_object('generates', false),
    'gutter_color', jsonb_build_object('generates', false),
    'ice_water_shield', jsonb_build_object('generates', false),
    'drip_edge', jsonb_build_object('generates', false),
    'scope_notes', jsonb_build_object('generates', false)
  )
)
where module_key = 'estimating'
  and org_id = '9d32b5a9-e11e-401b-8fa7-969065b004ce';
